export type FileKey = "texts" | "profile" | "promises" | "videos";

export type Section = { id: string; label: string; file: FileKey; path: string[]; routes?: string[] };

export const SECTIONS: Section[] = [
  { id: "start", label: "Startseite", file: "texts", path: ["start"], routes: ["/"] },
  { id: "profil", label: "Über mich — deine Daten", file: "profile", path: [], routes: ["/about"] },
  { id: "ueberMich", label: "Über mich — Seitentexte", file: "texts", path: ["ueberMich"] },
  { id: "versprechen", label: "Versprechen — deine Versprechen", file: "promises", path: [], routes: ["/promises"] },
  { id: "versprechenSeite", label: "Versprechen — Seitentexte", file: "texts", path: ["versprechenSeite"] },
  { id: "videoListe", label: "Videos — deine Videos", file: "videos", path: [], routes: ["/videos"] },
  { id: "videos", label: "Videos — Seitentexte", file: "texts", path: ["videos"] },
  { id: "spiele", label: "Spiele", file: "texts", path: ["spiele"], routes: ["/games"] },
  { id: "wettbewerb", label: "Wettbewerb", file: "texts", path: ["wettbewerb"], routes: ["/wettbewerb"] },
  { id: "blog", label: "Blog — Seitentexte", file: "texts", path: ["blog"], routes: ["/blog"] },
  { id: "eier", label: "Eier-Zerstörer", file: "texts", path: ["eierZerstoerer"], routes: ["/balls-destroyer"] },
  { id: "wieso", label: "Wieso-Seite", file: "texts", path: ["wieso"], routes: ["/wieso"] },
  { id: "datenschutz", label: "Datenschutz (deine Angaben + Text)", file: "texts", path: ["datenschutzSeite"], routes: ["/datenschutz"] },
  { id: "impressum", label: "Impressum", file: "texts", path: ["impressumSeite"], routes: ["/impressum"] },
  { id: "ueberall", label: "Überall (Menü, Fußzeile, Meldungen)", file: "texts", path: ["ueberall"] },
  { id: "404", label: "Fehlerseite (404)", file: "texts", path: ["seiteNichtGefunden"] },
];

const COMMON: Record<string, string> = {
  browserTitel: "Titel im Browser-Tab",
  ueberschrift: "Überschrift",
  untertitel: "Text unter der Überschrift",
  titel: "Titel",
  name: "Name",
  text: "Text",
  nummer: "Nummer",
  fensterTitel: "Fenstertitel (blaue Leiste)",
};

const TEXTS: Record<string, string> = {
  browserTitelAnhang: "Anhang an jeden Tab-Titel",
  beschreibungFuerGoogle: "Beschreibung für Google & Link-Vorschau",
  zumInhaltSpringen: "Tastatur-Link „Zum Inhalt springen“",
  navigation: "Menüpunkte (Menüleiste + Startmenü)",
  start: "Startseite",
  ueberMich: "Über mich",
  versprechen: "Versprechen",
  videos: "Videos",
  spiele: "Spiele",
  eierZerstoerer: "Eier-Zerstörer",
  blog: "Blog",
  keineBeitraege: "Text, wenn es noch keine Beiträge gibt",
  laden: "Text während die Beiträge laden",
  ladeFehler: "Text, wenn Laden fehlschlägt",
  nichtGefunden: "Text, wenn ein Beitrag nicht existiert",
  weiterlesen: "Link „Weiterlesen“",
  zurueck: "Link zurück zur Übersicht",
  lesezeit: "Lesezeit ({minuten} = Zahl)",
  neuerer: "Link zum neueren Beitrag",
  aelterer: "Link zum älteren Beitrag",
  vorschau: "Hinweis beim Drüberfahren / im Startmenü",
  statusleiste: "Statusleiste unten im Fenster",
  taskleisteStart: "Taskleiste: Start-Knopf",
  startMenueBanner: "Startmenü: senkrechter Schriftzug",
  uhrOrt: "Ort der Uhr (für Screenreader)",
  meldungMinimieren: "Meldung: Minimieren-Knopf geklickt",
  meldungSchliessen: "Meldung: Schließen-Knopf (✕) geklickt",
  fusszeile: "Fußzeile: Sprüche",
  fusszeileGeheimnisHinweis: "Fußzeile: Geheimnis-Hinweis",
  fusszeileKandidat: "Fußzeile: Wort „Kandidat“",
  fusszeileSchuljahr: "Fußzeile: Wort „Schuljahr“",
  zufallsZitat: "Dein Zitat (Startseite)",
  meldungLogo4x: "Meldung: Sushi-Symbol in der Titelleiste 4× geklickt",
  meldungLogo7x: "Meldung: Sushi-Symbol 7× geklickt (Sushi-Regen)",
  meldungSushiGetippt: "Meldung: „sushi“ getippt",
  meldungKonami: "Meldung: Konami-Code (Sushi-Regen)",
  platzhalterFehlt: "Text bei fehlenden Daten",
  willkommen: "Große Begrüßung",
  vorstellungSaetze: "Vorstellung: Sätze",
  vorstellungLink: "Vorstellung: letzter Satz (Link zur Wieso-Seite)",
  legalSatz: "Kleiner Satz unter der Vorstellung",
  versprechenUeberschrift: "Kasten „Versprechen“: Überschrift",
  versprechenAllesLesen: "Kasten „Versprechen“: Knopf",
  steckbriefUeberschrift: "Kasten „Steckbrief“: Überschrift",
  faktenName: "Steckbrief: „Name“",
  faktenKlasse: "Steckbrief: „Klasse“",
  faktenSchule: "Steckbrief: „Schule“",
  faktenSchuljahr: "Steckbrief: „Schuljahr“",
  faktenKandidatur: "Steckbrief: „Kandidatur“",
  faktenStatus: "Steckbrief: „Status“",
  faktenStatusWert: "Steckbrief: Status-Wert",
  zitatQuelle: "Zitat: Quelle darunter",
  mehrUeberschrift: "Kasten mit Knöpfen unten: Überschrift",
  reiterAllgemein: "Reiter über der Tabelle",
  quelleWort: "Wort vor der Quelle",
  felder: "Tabelle: Zeilen-Titel und Quellen",
  quelle: "Quelle (klein, rechts)",
  spitzname: "Spitzname",
  schule: "Schule",
  klasse: "Klasse",
  alter: "Alter",
  status: "Status",
  selbstbeschreibung: "Selbstbeschreibung",
  interessen: "Interessen",
  hobbies: "Hobbies",
  faehigkeiten: "Fähigkeiten",
  schwaechen: "Schwächen",
  charakter: "Charakter",
  zufallsfakt: "Zufallsfakt",
  statusWert: "Status-Wert",
  zufallsfaktHinweis: "Hinweis neben leerem Zufallsfakt",
  beweisstueck: "Top 10: „Beweisstück A“",
  top10: "Top 10: „Top 10“",
  top10Untertitel: "Top 10: Untertitel",
  richtigTitel: "Richtige Schreibweise: Überschrift",
  richtigName: "Richtige Schreibweise: großer Name",
  richtigSatz: "Richtige Schreibweise: Satz",
  weiterKnopf: "Knopf unten",
  detailsFolgen: "Stempel „Details folgen“",
  aktenzeichen: "Versprechen 6: Aktenzeichen",
  grossNachVersprechen6: "Versprechen 6: Riesensatz",
  unterschriftZeile: "Versprechen 6: Zeile unter der Unterschrift",
  dokumentName: "Versprechen 6: Fenstertitel des Editors",
  sieheAuchKnopf: "Knopf zum Eier-Zerstörer",
  baenderGefunden: "Info: „… Bänder gefunden“",
  nochInProduktion: "Info: „… noch in Produktion“",
  budget: "Info: Budget",
  keinSignal: "Platzhalter-Video: große Schrift",
  materialFolgt: "Platzhalter-Video: kleine Schrift",
  abspielen: "Abspielen-Knopf",
  aufnahme: "Aufnahme-Anzeige",
  spielTitel: "Spiel: Titel",
  spielUntertitel: "Spiel: Untertitel",
  soGehts: "Spiel: Anleitung",
  steuerung: "Spielfeld: Steuerung",
  startKnopf: "Spielfeld: Start-Knopf",
  nochmalKnopf: "Spielfeld: Nochmal-Knopf",
  ueberlebt: "Anzeige: Überlebt",
  rekord: "Anzeige: Rekord",
  erwischtVon: "Nach dem Verlieren: „Erwischt von“",
  spielerFigur: "Text auf deiner Spielfigur",
  fallendeWoerter: "Fallende Wörter",
  urteilUnter5Sekunden: "Ergebnis unter 5 Sekunden",
  urteilUnter15Sekunden: "Ergebnis unter 15 Sekunden",
  urteilUnter30Sekunden: "Ergebnis unter 30 Sekunden",
  urteilAb30Sekunden: "Ergebnis ab 30 Sekunden",
  warnband: "Rotes Warnband",
  warnbandNachAblauf: "Rotes Warnband (nach Ablauf)",
  ueberschriftNachAblauf: "Große Überschrift (nach Ablauf)",
  unterzeileKlein: "Zeile unter der Überschrift (klein)",
  unterzeileKleinNachAblauf: "Zeile unter der Überschrift (klein, nach Ablauf)",
  unterzeileGross: "Zeile unter der Überschrift (grün)",
  unterzeileGrossNachAblauf: "Zeile unter der Überschrift (grün, nach Ablauf)",
  einheiten: "Einheiten unter den Ziffern",
  satzUnterTimer: "Satz unter dem Countdown",
  fussnote: "Fußnote (Link zu Versprechen 6)",
  nachAblaufGross: "Nach Ablauf: große Zeile",
  nachAblaufSatz: "Nach Ablauf: Satz",
  nachAblaufKnopf: "Nach Ablauf: Knopf",
  statusSystem: "Status: Sicherheitssystem",
  statusSystemAktiv: "Status: System aktiv",
  statusSystemAus: "Status: System aus",
  statusTitel: "Status: Überschrift",
  statusSicher: "Status: sicher",
  statusZerstoert: "Status: zerstört",
  bedrohungsstufe: "Status: Bedrohungsstufe",
  integritaet: "Status: Integrität",
  integritaetWert: "Status: Integrität-Wert",
  systemmeldung: "Status: Systemmeldung",
  sprueche: "Wechselnde Sprüche (je nach Restzeit)",
  mehrAls7Tage: "mehr als 7 Tage übrig",
  mehrAls3Tage: "mehr als 3 Tage übrig",
  mehrAls24Stunden: "mehr als 24 Stunden übrig",
  mehrAls6Stunden: "mehr als 6 Stunden übrig",
  mehrAls1Stunde: "mehr als 1 Stunde übrig",
  mehrAls10Minuten: "mehr als 10 Minuten übrig",
  mehrAls1Minute: "mehr als 1 Minute übrig",
  letzteMinute: "letzte Minute",
  nachAblauf: "nach Ablauf",
  zielWien: "Ziel (Wien)",
  zielDeineUhr: "Ziel (deine Uhr)",
  naechsteGlocke: "Nächste Glocke in",
  naechsteGlockeNie: "Nächste Glocke (nach Ablauf)",
  tonAus: "Ton-Knopf: aus",
  tonAn: "Ton-Knopf: an",
  tonBlockiert: "Ton-Knopf: blockiert",
  tonKlickNoetig: "Ton-Knopf: Klick nötig",
  glockeTesten: "Knopf: Glocke testen",
  glockeErlauben: "Knopf: Glocke erlauben",
  tonHinweis: "Hinweis unter den Ton-Knöpfen",
  keinePanik: "Riesiger Blinktext unten",
  wettbewerb: "Wettbewerb",
  regelnUeberschrift: "Regeln: Überschrift",
  regeln: "Regeln (eine Zeile pro Schritt)",
  preisUeberschrift: "Preis: Überschrift",
  preis: "Preis — leer = „folgt“",
  einsendeschlussUeberschrift: "Einsendeschluss: Überschrift",
  einsendeschluss: "Einsendeschluss (z. B. 20.10.2026) — leer = „folgt“",
  regelnHinweis: "Hinweis: was verboten ist",
  datenschutz: "Datenschutz-Hinweis",
  galerieUeberschrift: "Hall of Fame: Überschrift",
  galerieLeer: "Hall of Fame: noch leer",
  galerieNichtVerbunden: "Hall of Fame: Supabase nicht verbunden",
  galerieFehler: "Hall of Fame: Ladefehler",
  platz: "Wort „Platz“",
  anonym: "Name, wenn keiner angegeben wurde",
  einsendenUeberschrift: "Einsenden-Fenster: Titel",
  nameFeld: "Einsenden: Feld Name",
  klasseFeld: "Einsenden: Feld Klasse",
  einverstanden: "Einsenden: Einverständnis-Häkchen",
  absendenKnopf: "Einsenden: Absenden-Knopf",
  sendet: "Einsenden: wird gesendet",
  gesendet: "Einsenden: erfolgreich",
  sendeFehler: "Einsenden: Fehler",
  datenschutzLink: "Link-Text zur Datenschutzerklärung",
  emailFeld: "Einsenden: Feld E-Mail",
  mindestalter: "Einsenden: Häkchen Mindestalter",
  vorschauHinweis: "Einsenden: Text über der Vorschau",
  pruefeName: "Fehler: Name ungültig",
  pruefeEmail: "Fehler: E-Mail ungültig",
  schonTeilgenommen: "Fehler: E-Mail hat schon teilgenommen",
  schonTeilgenommenGeraet: "Hinweis: dieses Gerät hat schon teilgenommen",
  ungueltig: "Fehler: Angaben ungültig",
  ladenHinweis: "YouTube: Hinweis vor dem Laden",
  ladenKnopf: "YouTube: Knopf „Video laden“",
  verantwortlicher: "Verantwortlicher (dein Name)",
  ort: "Dein Wohnort (z. B. Hollabrunn) — Pflicht fürs Impressum",
  kontaktEmail: "Kontakt-E-Mail — Pflicht",
  hosting: "Hosting-Anbieter mit Adresse (z. B. GitHub Pages, GitHub Inc., USA)",
  supabaseRegion: "Supabase-Region (beim Anlegen wählen: Frankfurt)",
  loeschfrist: "Wann Einsendungen und E-Mails gelöscht werden",
  stand: "Stand (Datum der letzten Änderung)",
  abschnitte: "Abschnitte",
  absaetze: "Absätze ({platzhalter} werden automatisch ersetzt)",
  standText: "Zeile ganz unten",
  fusszeileDatenschutz: "Fußzeile: Link „Datenschutz“",
  fusszeileImpressum: "Fußzeile: Link „Impressum“",
  nichtAktiv: "Einsenden: Supabase nicht verbunden",
  kopfzeile: "Fenstertitel",
  ladeMeldungen: "Wechselnde Lade-Meldungen",
  tipp: "Tipp",
  tippLink: "Tipp: Link",
  aufgeben: "Aufgeben-Link",
  abbrechenKnopf: "Abbrechen-Knopf",
  fehler: "Fehlermeldung: fette Zeile",
  satz: "Satz",
  knopf: "Knopf",
};

const PROFILE: Record<string, string> = {
  vorname: "Vorname",
  nachname: "Nachname",
  spitzname: "Spitzname",
  schule: "Schule",
  schuljahr: "Schuljahr",
  kandidatur: "Kandidiert als",
  klasse: "Klasse (z. B. 3AHIT) — leer = Platzhalter",
  alter: "Alter — leer = Platzhalter",
  interessen: "Interessen (z. B. Schach / CS2) — leer = Platzhalter",
  hobbies: "Hobbies — leer = Platzhalter",
  faehigkeiten: "Fähigkeiten — leer = Platzhalter",
  schwaechen: "Schwächen — leer = Platzhalter",
  charakter: "Charakter — leer = Platzhalter",
  zufallsfakt: "Zufallsfakt — leer = Platzhalter",
  selbstbeschreibung: "Selbstbeschreibung",
  lehrerNamen: "Top 10: falsche Namen",
  notiz: "Notiz in Klammern (optional)",
};

const PROMISES: Record<string, string> = {
  zwischenruf: "Zwischenruf vor Versprechen 6",
  liste: "Versprechen",
  ueberschriftKlein: "Kleine grüne Zeile über dem Titel",
  kurzfassung: "Kurzfassung (Karte auf der Startseite)",
  absaetze: "Absätze",
  punkte: "Unterpunkte",
  detailsFolgenStempel: "Stempel „Details folgen“ anzeigen",
};

const VIDEOS: Record<string, string> = {
  beschreibung: "Beschreibung — leer = Platzhalter",
  youtubeId: "YouTube-Link (einfach den ganzen Link einfügen)",
  dauer: "Länge (z. B. 2:31, optional)",
  titel: "Titel — leer = Platzhalter",
};

const BY_FILE: Record<FileKey, Record<string, string>> = { texts: TEXTS, profile: PROFILE, promises: PROMISES, videos: VIDEOS };

export function labelFor(file: FileKey, key: string): string {
  return (
    BY_FILE[file][key] ??
    COMMON[key] ??
    key.replace(/([a-z])([A-Z0-9])/g, "$1 $2").replace(/^./, (c) => c.toUpperCase())
  );
}
